# Configuration database for development purposes

spring:
  datasource:

    url: your_database_url_here
    driver-class-name: org.postgresql.Driver
    username: your_username_here
    password: your_password_here

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: your_dialect_here