# Configuration postgreSQL database for development purposes

spring:
  config:
    import: optional:file:./.env  #  datasource:

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect